import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NewTopic from "./newTopic.js";
import { Button, Heading } from "@chakra-ui/react";
import { useState } from "react";
import AuthScreen from "./authScreen.js";
import authMiddleware from "./api/checkAuth.js";

export async function getServerSideProps(context) {
  const { req } = context;

  try {
    const user = await authMiddleware(req);

    return {
      props: { user: user || null },
    };
  } catch (error) {
    console.error("Authentication error:", error.message);
    return {};
  }
}

export default function Home({ user }) {
  console.log("HELLO");
  console.log(user);
  const [auth, setAuth] = useState(!!user); //!! makes it false if its null

  async function handleLogout() {
    try {
      const res = await fetch("/api/logout", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
      });

      setAuth(false);
    } catch (error) {
      console.error("Error logging out:", error);
    }
  }
  function Page() {
    if (auth) {
      return <><NewTopic username = {user}/>;<Button
      position={"absolute"}
      left={"90vw"}
      top={"5vh"}
      transform={"translate(0%,0%)"}

      onClick={() => {
        handleLogout();
      }}
    >
      Log out
    </Button>
    </>
    }
    return <AuthScreen />;
  }
  return (
    <>
      <Head>
        <title>SelfStudy App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Heading
          textAlign={"center"}
          position={"absolute"}
          left={"50vw"}
          top={"5vh"}
          transform={"translate(-50%)"}
          size="3xl"
        >
          SelfStudy
        </Heading>

        
        <Page />
      </main>
    </>
  );
}
